### ISSUE TITLE
Post processing and IVA

### ISSUE THREAD

**Issue by vulkans22** [shadowmage45/TUFX#21]
I'm not sure if it's intended behaviour, if it is then disregard and close- currently post processing effects aren't being applied to the internal space layer. Switching to IVA view and modifying effect parameters causes the world space outside to correctly change, but the internal model and props remain unaffected.

Congrats on release of the mod!

**Comment by shadowmage45** [comment]
Thanks, will definitely take a look at it.  From my initial inference, there is likely a secondary 'IVA' camera in the scene, which will need to have the PostProcessLayer (and possibly PostProcessVolume) components added onto it.

KSP essentially renders IVAs as a completely separate scene; at a different world-position, and with a different camera than that which renders the Flight scene, and it is likely these differences that are causing the effects to not appear in IVAs.

Unsure if it is desirable to have the effects applied in IVAs, but I'll at least have to do some testing to see what it looks like / if there are any issues with their use in that setup.

**Comment by vulkans22** [comment]
The Antialias effects in particular I think would be desirable for IVA, as IVAs (Particularly when running RPM along with ASET props) tend to use very fine lines and small text, I bet it would look much better with TAA applied on top. Thanks for your time looking into it.
