### ISSUE TITLE
Colour grading 'Gamma' value does not load from profile config file

### ISSUE THREAD

**Issue by bysamjiang** [shadowmage45/TUFX#24]
Hello there!
I noticed that the gamma values were not being read from the TUFX profile config file — it was quite frustrating to manually enter it each time, but fortunately (especially as I don't code), I did find the reason why and also a fix.

**Solution:**
_There is a missing line in_ `Plugin\TUFX\PostProcessing\Effects\ColorGrading.cs`.
This needs to be added after _Line 419_: `loadVector4Parameter(config, "Gamma", gamma);`

**Comment by brihernandez** [comment]
I've come across the same exact issue. Gamma seems to save correctly when exported, but does not load.

**Comment by JonnyOThan** [comment]
Fixed in 75902a1
