### ISSUE TITLE
Enabling HDR makes some parts partially transparent

### ISSUE THREAD

**Issue by JonnyOThan** [shadowmage45/TUFX#30]
Current theory on the "transparency" issue is that when HDR is enabled, the alpha channel exceeds 1.0 which causes the underlying colors to come out inverted (assuming some kind of blend algorithm like `alpha * color_1 + (1-alpha)*color_2`).  In this image, the blue sky becomes orange inside the fairing, the dark flagpole and trim around the cockpit come out light, and the white parts of the cockpit come out dark.

![image](https://user-images.githubusercontent.com/9804078/172932236-c1577b57-2e2f-400c-8995-7500bb6b89c6.png)

Textures Unlimited already has the ability to replace the shaders used for various models.  I successfully did a simple test of the mobile processing lab, where previously I could see the ladder parts on the other side of it.

The other test case I was using (and where I notice this problem most often) is with fairings.  But since the fairing is not a standard model, I don't think TexturesUnlimited can patch it (but I only just started using TU an hour ago, so maybe I'm missing something).  It would also be prohibitive to list EVERY model in the game for TU to patch, and wouldn't help non-stock parts that use the broken stock shaders.

It *may* be possible to create a mod that uses TU and entirely replaces the stock shaders with TU's versions at runtime, which would *just fix* this problem for everyone.

Shabby also looks promising: https://github.com/taniwha/Shabby

**Comment by BTAxis** [comment]
I encountered a part that is transparent even with HDR turned off. The part is from Kerbal Planetary Base Systems. The screenshot was taken using the default-empty profile.
![image](https://user-images.githubusercontent.com/119742/188440577-138b6273-4aca-480e-8e57-462b363ee3b5.png)

**Comment by JonnyOThan** [comment]
> I encountered a part that is transparent even with HDR turned off. The part is from Kerbal Planetary Base Systems. The screenshot was taken using the default-empty profile.
> ![image](https://user-images.githubusercontent.com/119742/188440577-138b6273-4aca-480e-8e57-462b363ee3b5.png)

Please include your log file and a screenshot with the tufx editor gui opened.

**Comment by BTAxis** [comment]
Here's the log and the screenshot.
[Player.log.zip](https://github.com/shadowmage45/TUFX/files/9491816/Player.log.zip)
![tufx](https://user-images.githubusercontent.com/119742/188507145-4bdeda31-e3cd-4032-a63e-b82796524d10.jpg)

The transparency only seems to occur if the part is in sunlight, as opposed to artificial light sources.

**Comment by JonnyOThan** [comment]
> Here's the log and the screenshot. [Player.log.zip](https://github.com/shadowmage45/TUFX/files/9491816/Player.log.zip) ![tufx](https://user-images.githubusercontent.com/119742/188507145-4bdeda31-e3cd-4032-a63e-b82796524d10.jpg)

Can you try this without TUFX installed and see if it still occurs?  I just saw a report that planetshine can also cause this, but you don't have that.  But it means other rendering-related mods could also be the culprit.

**Comment by BTAxis** [comment]
I removed TUFX, and now the part looks normal. Since I use CKAN to manage my mods, removing TUFX also removed my installations of SRB Waterfall Effects and Real Plume. So, it's possible those mods are involved.
