### ISSUE TITLE
Flickering Earth after update to 1.0.5.0

### ISSUE THREAD

**Issue by Test-Account-KSP** [shadowmage45/TUFX#34]
RSS/RO. Earth is flickering in map view after updating from 1.0.4.0 to 1.0.5.0.  Reverting to 1.0.4.0 stopped the flickering.

**Comment by JonnyOThan** [comment]
This is an unfortunate side effect of the changes to default profiles for pre-existing saves.  Prior to 1.0.5, map mode used default-flight.  If you started your save before 1.0.5 then your map mode will use default-flight, and then after the upgrade this profile has TAA enabled.  1.0.5 also changed the default profile for map mode to default-trackingstation, but unfortunately this doesn't help people who already have saves in progress.

The good news is that you can still use 1.0.5, just go into map mode and change the profile to default-trackingstation.  You should only need to do this once.
