### ISSUE TITLE
(AA) All AA settings aside from TemporalAA cause bad pixel vibration, especially at distance

### ISSUE THREAD

**Issue by Dupiter-AU** [shadowmage45/TUFX#37]
I tried to record this, but the only way it could be visible on video was at really high quality, and that caused the video to have a large file size which couldn't be sent over GitHub, so I don't have any video evidence to support this.

The effects happen across all TUFX profiles which use AA; I tested both stock and BallisticFox profiles. Even the "None" Anti Aliasing setting caused pixel vibration, which is really weird to me. The only way to stop the effects were to use TemporalAA instead, but that introduced massive blur when moving the camera, which I really don't like.

I'm not sure what could be causing this, but for reference, my screen res is 2560x1440 155Hz, I'm not hitting the max framerate, I don't have Vsync or Anti Aliasing enabled in KSP settings (although changing AA settings didn't seem to affect anything), and I'm running KSP through Proton, because I use Arch Linux

Heres my KSP.log file for reference:
[KSP.log](https://github.com/shadowmage45/TUFX/files/10610351/KSP.log)

Thanks

EDIT: I should also note that I _have_ seen issue #19, but I don't think it relates here at it seems to be only affecting land, whereas here it affects everything and it's caused by all aside from TAA

**Comment by JonnyOThan** [comment]
This sounds like the symptom caused by temporal antialiasing from scatterer.  Try turning that off or uninstalling scatterer and trying again.

**Comment by Dupiter-AU** [comment]
Disabling TAA in Scatterer worked, thanks for the help!
