### ISSUE TITLE
[1.0.7.0] Flight scene becomes blurry in space when HDR and Depth of Field are enabled

### ISSUE THREAD

**Issue by eminterrupted** [shadowmage45/TUFX#41]
**Summary**
After updating to 1.0.7.0 via CKAN, enabling HDR along with Depth of Field causes the planet and skybox to blur heavily when in space. The UI is unaffected. Disabling either HDR or Depth of Field immediately resolves the issue. Other modules have no effect. I am using RSS-Reborn and VolumetricClouds if that factors in at all.

**Min Version**
1.0.7.0 (Does not repro on 1.0.6.0)

**Repro steps**:
- Place a vessel into orbit (launch, KCT, HyperEdit, whatever)
- Open the TUFX Menu
- Choose any profile (can even be a default empty one)
- Enable HDR
- Enable Depth of Field (with or without parameters enabled)

**Expected Result**: HDR and Depth of Field can both be enabled simultaneously
**Actual Result**: Using both causes blurry planet and skybox textures

**Examples**
[HDR Disabled, Depth of Field Enabled](https://i.imgur.com/MJQ7tg0.jpg) (no issue)

[HDR Enabled, Depth of Field Enabled](https://i.imgur.com/NT00sYK.jpg) (repro)

**KSPLog**
No errors / exceptions I could find related to TUFX, but it's available [here](https://1drv.ms/u/s!AmAxSBcQL19WrPsPTPw798uLt2cT7w?e=wtWxuw) if it would be useful.

**Comment by ballisticfox** [comment]
Sounds like a lot of the issues that used to be tracking station only have been carried over to Scaled Space too now

**Comment by JonnyOThan** [comment]
Are there any DOF settings that make the planet *not* blurry?  It seems like HDR alters how DOF is applied (this has always been the case).  The difference now is that the flight profile is also being applied to the scaledspace camera.

**Comment by eminterrupted** [comment]
It looks like the only field in DOF that makes a slight difference is Kernel Size. With that enabled, setting it to Small reduces blur but does not eliminate it entirely. Disabling it appears to be equivalent to setting it to Medium. All of the other fields either do nothing or make it more blurry.
