### ISSUE TITLE
Add Dynamic 'Depth of Field' configuration option

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TUFX#5]
To update the depth-of-field focus values/etc based on the current camera distance from the vessel (flight), terrain at center of camera (space-center), or focused body (map views).

Also depending on scene, should widen the 'clarity' range to keep nearby bodies mostly in focus (map scenes, when focused on an orbiting craft).

This will need to be both a parameter on the DepthOfField settings, and some additional scripting added to animate these values based on current game state (unknown where this code would reside...).

https://docs.unity3d.com/Packages/com.unity.postprocessing@2.1/manual/Depth-of-Field.html

**Comment by jrodrigv** [comment]
I did realize yesterday about this during my testing.

I have some code to calculate the focal length when the useCameraFov is active in KS3P (Which I think it is part of the V1 PostProcessing stack) https://github.com/c1usta/KS3P/blob/patch/Unity.cs#L1154

**Comment by shadowmage45** [comment]
Thanks, I'll definitely take a look over it.  Still undecided on whether I should implement this feature; seems like it would be nice to have, but I'm also trying to stay 'hands off' of the Post Process configuration.
