### ISSUE TITLE
HDR seems to cause a strange black sphere around planets when the sun is not in view

### ISSUE THREAD

**Issue by JonnyOThan** [shadowmage45/TUFX#52]
![image](https://github.com/shadowmage45/TUFX/assets/9804078/92bcceac-bcb6-40b1-99d6-499d0bc0afdc)

Probably related to eve/scatterer, but it goes away when HDR is disabld.

**Comment by AMPW-german** [comment]
I also experience this, after removing spectra it went away, maybe some of the removed dependecies were a problem but disabling hdr in tufx fixes this.

**Comment by JonnyOThan** [comment]
this has been moved: https://github.com/KSPModStewards/TUFX/issues/7
