### ISSUE TITLE
Add support for post-processing in editor scenes

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TUFX#8]
Currently, referencing either Camera.main or EditorCamera.fetch.cam results in... strange things in the editor; the building geometry and other 3d rendered objects are not kept in-sync.

Until this is resolved, profiles have been disabled in the editor scene.

**Comment by abrenneke** [comment]
I tried out both `EditorCamera.Instance.cam` and `EditorLogic.fetch.editorCamera` and they both seem to... work okay? I don't notice anything wrong, and maybe you're done with modding now but how can I reproduce the problems @shadowmage45?

![image](https://user-images.githubusercontent.com/342540/202873943-c76bf959-d539-487f-a5ad-c4013b1bfb44.png)
